### ISSUE TITLE
[misc]  dataset && dreambooth details

### ISSUE THREAD

**Issue by xdobetter** [zeng-yifei/AvatarBooth#1]
Hello, I am interested in excellent work.
I have three problems with your paper:
1. Can you share your personalization datasets? I want to verify the result.

2. Could you share more details about the dreambooth? E.g., What are the lr and iter values ​​for dreambooth face and full-body?

3. Which open-source version of dreambooth3d are you using?

**Comment by zeng-yifei** [comment]
Hi, thank you for your attention. For your question: 
1. For privacy concerns, we can't provide the dataset publicly. You can contact my email and ask for it.
2. lr used for DreamBooth is 1e-6 in diffusers. Iters' settings are written in the paper.
3. I followed the DB3D paper to implement a version on my own.

**Comment by xdobetter** [comment]
Thank you very much for your reply, I am sorry to find not  your email, could you share your email~:)
for dreambooth face and body. Are their learning rates both 1e-6?

**Comment by zeng-yifei** [comment]
Hi, my email is 522023230156@smail.nju.edu.cn . Welcome to contact with me. 

And yes, lr was the same for both face and body.
